services:
  metabase:
    image: metabase/metabase
    container_name: metabase
    ports:
      - "3000:3000"

  project_master_metabase:
    build: .
    container_name: project_master_metabase
    ports:
      - "5001:5001"
    volumes:
       # Allows the Flask container to run Docker commands (e.g., stop/restart Metabase)
      - /var/run/docker.sock:/var/run/docker.sock